### ISSUE TITLE
Consecutive archiving throws error

### ISSUE THREAD

**Issue by Atakannbal** [Atakannbal/XClude#2]
**Describe the bug**
Consecutive archiving operations are not processed

**To Reproduce**
1. Start the application 
2. Choose output directory -> drag your folder to zip -> Choose excluded folders
3. Press submit
4. Repeat the steps 2 & 3 OR just 3
5. You should see the error

**Desktop**
 - OS: [ macOS Big Sur ]
 - Version [ Version 11.1 ]

**Additional context**
```
ArchiverError: queue closed
    at Archiver.directory (/Users/kns/Desktop/TUT/my-electron-app/node_modules/archiver/lib/core.js:607:24)
    at /Users/kns/Desktop/TUT/my-electron-app/services/zip/create-zip.js:59:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/kns/Desktop/TUT/my-electron-app/services/zip/create-zip.js:57:14) {
  code: 'QUEUECLOSED',
  data: undefined
}
```

**Comment by ademkoc** [comment]
Thank you for creating issue.

I found the problem, i will fix this today.

**Comment by Atakannbal** [comment]
@admkc Thanks!
